name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v3

      # 2. Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install dependencies
      - run: |
          cd frontend
          npm install

      # 4. Build the frontend
      - run: |
          cd frontend
          npm run build

      # 5. Deploy to GitHub Pages
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: frontend/build
